# -*- coding=utf-8 -*-

"""
sentry-dingtalk

An extension for Sentry which integrates with DingTalk, which will
send notification to DingTalk group by webhook urls generated by your rebot.
"""

from setuptools import setup, find_packages

setup(
    name='sentry-dingtalk',
    version='1.0.0',
    author='hifiveszu',
    author_email='hifiveszu@gmail.com',
    url='https://github.com/hifiveszu/sentry-dingtalk',
    description='A Sentry extension which integrates with Dingtalk.',
    long_description=__doc__,
    license='BSD',
    packages=find_packages(),
    zip_safe=False,
    install_requires=[
        "sentry>=5.4.1",
    ],
    entry_points={
        'sentry.plugins': [
            'dingtalk = sentry_dingtalk.plugin:DingTalkPlugin'
        ],
    },
    include_package_data=True,
    classifiers=[
        'Framework :: Django',
        'Intended Audience :: Developers',
        'Intended Audience :: System Administrators',
        'Operating System :: OS Independent',
        'Topic :: Software Development'
    ]
)
